spring:
  application:
    name: devConnectBackend
  data:
    mongodb:
      uri: mongodb://localhost:27017/devConnect
  jackson:
    deserialization:
      fail-on-unknown-properties: true

server:
  error:
    include-message: always
    include-binding-errors: always
